// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: iiqka/proto-api/motion-external/control_attributes.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Kuka.Motion.External {

  /// <summary>Holder for reflection information generated from iiqka/proto-api/motion-external/control_attributes.proto</summary>
  public static partial class ControlAttributesReflection {

    #region Descriptor
    /// <summary>File descriptor for iiqka/proto-api/motion-external/control_attributes.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ControlAttributesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjhpaXFrYS9wcm90by1hcGkvbW90aW9uLWV4dGVybmFsL2NvbnRyb2xfYXR0",
            "cmlidXRlcy5wcm90bxIUa3VrYS5tb3Rpb24uZXh0ZXJuYWwiRQofSm9pbnRJ",
            "bXBlZGFuY2VDb250cm9sQXR0cmlidXRlcxIRCglzdGlmZm5lc3MYASADKAES",
            "DwoHZGFtcGluZxgCIAMoASKBAQojQ2FydGVzaWFuSW1wZWRhbmNlQ29udHJv",
            "bEF0dHJpYnV0ZXMSEQoJc3RpZmZuZXNzGAEgAygBEg8KB2RhbXBpbmcYAiAD",
            "KAESGwoTbnVsbHNwYWNlX3N0aWZmbmVzcxgDIAMoARIZChFudWxsc3BhY2Vf",
            "ZGFtcGluZxgEIAMoAUKJAQoYY29tLmt1a2EubW90aW9uLmV4dGVybmFsQhpD",
            "b250cm9sU2lnbmFsSW50ZXJuYWxQcm90b1ABWjhnb2xhbmcucmQua3VrYS5j",
            "b20vbW90aW9uLWFwaS9wcm90by9rdWthL21vdGlvbi9leHRlcm5hbKoCFEt1",
            "a2EuTW90aW9uLkV4dGVybmFsYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Kuka.Motion.External.JointImpedanceControlAttributes), global::Kuka.Motion.External.JointImpedanceControlAttributes.Parser, new[]{ "Stiffness", "Damping" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Kuka.Motion.External.CartesianImpedanceControlAttributes), global::Kuka.Motion.External.CartesianImpedanceControlAttributes.Parser, new[]{ "Stiffness", "Damping", "NullspaceStiffness", "NullspaceDamping" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Type to describe the attributes specific to the joint impedance control mode.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class JointImpedanceControlAttributes : pb::IMessage<JointImpedanceControlAttributes>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<JointImpedanceControlAttributes> _parser = new pb::MessageParser<JointImpedanceControlAttributes>(() => new JointImpedanceControlAttributes());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<JointImpedanceControlAttributes> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Kuka.Motion.External.ControlAttributesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public JointImpedanceControlAttributes() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public JointImpedanceControlAttributes(JointImpedanceControlAttributes other) : this() {
      stiffness_ = other.stiffness_.Clone();
      damping_ = other.damping_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public JointImpedanceControlAttributes Clone() {
      return new JointImpedanceControlAttributes(this);
    }

    /// <summary>Field number for the "stiffness" field.</summary>
    public const int StiffnessFieldNumber = 1;
    private static readonly pb::FieldCodec<double> _repeated_stiffness_codec
        = pb::FieldCodec.ForDouble(10);
    private readonly pbc::RepeatedField<double> stiffness_ = new pbc::RepeatedField<double>();
    /// <summary>
    /// Joint stiffness values
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<double> Stiffness {
      get { return stiffness_; }
    }

    /// <summary>Field number for the "damping" field.</summary>
    public const int DampingFieldNumber = 2;
    private static readonly pb::FieldCodec<double> _repeated_damping_codec
        = pb::FieldCodec.ForDouble(18);
    private readonly pbc::RepeatedField<double> damping_ = new pbc::RepeatedField<double>();
    /// <summary>
    /// Joint damping values
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<double> Damping {
      get { return damping_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as JointImpedanceControlAttributes);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(JointImpedanceControlAttributes other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!stiffness_.Equals(other.stiffness_)) return false;
      if(!damping_.Equals(other.damping_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= stiffness_.GetHashCode();
      hash ^= damping_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      stiffness_.WriteTo(output, _repeated_stiffness_codec);
      damping_.WriteTo(output, _repeated_damping_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      stiffness_.WriteTo(ref output, _repeated_stiffness_codec);
      damping_.WriteTo(ref output, _repeated_damping_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += stiffness_.CalculateSize(_repeated_stiffness_codec);
      size += damping_.CalculateSize(_repeated_damping_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(JointImpedanceControlAttributes other) {
      if (other == null) {
        return;
      }
      stiffness_.Add(other.stiffness_);
      damping_.Add(other.damping_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10:
          case 9: {
            stiffness_.AddEntriesFrom(input, _repeated_stiffness_codec);
            break;
          }
          case 18:
          case 17: {
            damping_.AddEntriesFrom(input, _repeated_damping_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10:
          case 9: {
            stiffness_.AddEntriesFrom(ref input, _repeated_stiffness_codec);
            break;
          }
          case 18:
          case 17: {
            damping_.AddEntriesFrom(ref input, _repeated_damping_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Type to describe the attributes specific to the cartesion impedance control mode.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CartesianImpedanceControlAttributes : pb::IMessage<CartesianImpedanceControlAttributes>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CartesianImpedanceControlAttributes> _parser = new pb::MessageParser<CartesianImpedanceControlAttributes>(() => new CartesianImpedanceControlAttributes());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CartesianImpedanceControlAttributes> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Kuka.Motion.External.ControlAttributesReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CartesianImpedanceControlAttributes() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CartesianImpedanceControlAttributes(CartesianImpedanceControlAttributes other) : this() {
      stiffness_ = other.stiffness_.Clone();
      damping_ = other.damping_.Clone();
      nullspaceStiffness_ = other.nullspaceStiffness_.Clone();
      nullspaceDamping_ = other.nullspaceDamping_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CartesianImpedanceControlAttributes Clone() {
      return new CartesianImpedanceControlAttributes(this);
    }

    /// <summary>Field number for the "stiffness" field.</summary>
    public const int StiffnessFieldNumber = 1;
    private static readonly pb::FieldCodec<double> _repeated_stiffness_codec
        = pb::FieldCodec.ForDouble(10);
    private readonly pbc::RepeatedField<double> stiffness_ = new pbc::RepeatedField<double>();
    /// <summary>
    /// Cartesian stiffness values (xyzabc)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<double> Stiffness {
      get { return stiffness_; }
    }

    /// <summary>Field number for the "damping" field.</summary>
    public const int DampingFieldNumber = 2;
    private static readonly pb::FieldCodec<double> _repeated_damping_codec
        = pb::FieldCodec.ForDouble(18);
    private readonly pbc::RepeatedField<double> damping_ = new pbc::RepeatedField<double>();
    /// <summary>
    /// Cartesian damping values (xyzabc)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<double> Damping {
      get { return damping_; }
    }

    /// <summary>Field number for the "nullspace_stiffness" field.</summary>
    public const int NullspaceStiffnessFieldNumber = 3;
    private static readonly pb::FieldCodec<double> _repeated_nullspaceStiffness_codec
        = pb::FieldCodec.ForDouble(26);
    private readonly pbc::RepeatedField<double> nullspaceStiffness_ = new pbc::RepeatedField<double>();
    /// <summary>
    /// Cartesian stiffness values for nullspaces of robot
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<double> NullspaceStiffness {
      get { return nullspaceStiffness_; }
    }

    /// <summary>Field number for the "nullspace_damping" field.</summary>
    public const int NullspaceDampingFieldNumber = 4;
    private static readonly pb::FieldCodec<double> _repeated_nullspaceDamping_codec
        = pb::FieldCodec.ForDouble(34);
    private readonly pbc::RepeatedField<double> nullspaceDamping_ = new pbc::RepeatedField<double>();
    /// <summary>
    /// Cartesian damping values for nullspaces of robot
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<double> NullspaceDamping {
      get { return nullspaceDamping_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CartesianImpedanceControlAttributes);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CartesianImpedanceControlAttributes other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!stiffness_.Equals(other.stiffness_)) return false;
      if(!damping_.Equals(other.damping_)) return false;
      if(!nullspaceStiffness_.Equals(other.nullspaceStiffness_)) return false;
      if(!nullspaceDamping_.Equals(other.nullspaceDamping_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= stiffness_.GetHashCode();
      hash ^= damping_.GetHashCode();
      hash ^= nullspaceStiffness_.GetHashCode();
      hash ^= nullspaceDamping_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      stiffness_.WriteTo(output, _repeated_stiffness_codec);
      damping_.WriteTo(output, _repeated_damping_codec);
      nullspaceStiffness_.WriteTo(output, _repeated_nullspaceStiffness_codec);
      nullspaceDamping_.WriteTo(output, _repeated_nullspaceDamping_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      stiffness_.WriteTo(ref output, _repeated_stiffness_codec);
      damping_.WriteTo(ref output, _repeated_damping_codec);
      nullspaceStiffness_.WriteTo(ref output, _repeated_nullspaceStiffness_codec);
      nullspaceDamping_.WriteTo(ref output, _repeated_nullspaceDamping_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += stiffness_.CalculateSize(_repeated_stiffness_codec);
      size += damping_.CalculateSize(_repeated_damping_codec);
      size += nullspaceStiffness_.CalculateSize(_repeated_nullspaceStiffness_codec);
      size += nullspaceDamping_.CalculateSize(_repeated_nullspaceDamping_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CartesianImpedanceControlAttributes other) {
      if (other == null) {
        return;
      }
      stiffness_.Add(other.stiffness_);
      damping_.Add(other.damping_);
      nullspaceStiffness_.Add(other.nullspaceStiffness_);
      nullspaceDamping_.Add(other.nullspaceDamping_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10:
          case 9: {
            stiffness_.AddEntriesFrom(input, _repeated_stiffness_codec);
            break;
          }
          case 18:
          case 17: {
            damping_.AddEntriesFrom(input, _repeated_damping_codec);
            break;
          }
          case 26:
          case 25: {
            nullspaceStiffness_.AddEntriesFrom(input, _repeated_nullspaceStiffness_codec);
            break;
          }
          case 34:
          case 33: {
            nullspaceDamping_.AddEntriesFrom(input, _repeated_nullspaceDamping_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10:
          case 9: {
            stiffness_.AddEntriesFrom(ref input, _repeated_stiffness_codec);
            break;
          }
          case 18:
          case 17: {
            damping_.AddEntriesFrom(ref input, _repeated_damping_codec);
            break;
          }
          case 26:
          case 25: {
            nullspaceStiffness_.AddEntriesFrom(ref input, _repeated_nullspaceStiffness_codec);
            break;
          }
          case 34:
          case 33: {
            nullspaceDamping_.AddEntriesFrom(ref input, _repeated_nullspaceDamping_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
