// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: iiqka/proto-api/motion-external/motion_state_internal.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Kuka.Motion.External {

  /// <summary>Holder for reflection information generated from iiqka/proto-api/motion-external/motion_state_internal.proto</summary>
  public static partial class MotionStateInternalReflection {

    #region Descriptor
    /// <summary>File descriptor for iiqka/proto-api/motion-external/motion_state_internal.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MotionStateInternalReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjtpaXFrYS9wcm90by1hcGkvbW90aW9uLWV4dGVybmFsL21vdGlvbl9zdGF0",
            "ZV9pbnRlcm5hbC5wcm90bxIUa3VrYS5tb3Rpb24uZXh0ZXJuYWwaK2lpcWth",
            "L3Byb3RvLWFwaS9tb3Rpb24tZXh0ZXJuYWwvdXRpbHMucHJvdG8aO2lpcWth",
            "L3Byb3RvLWFwaS9tb3Rpb24tZXh0ZXJuYWwvZXh0ZXJuYWxfY29udHJvbF9t",
            "b2RlLnByb3RvIq8CChNNb3Rpb25TdGF0ZUludGVybmFsEhMKC2lwb19zdG9w",
            "cGVkGAEgASgIEj8KDGNvbnRyb2xfbW9kZRgCIAEoDjIpLmt1a2EubW90aW9u",
            "LmV4dGVybmFsLkV4dGVybmFsQ29udHJvbE1vZGUSQAoSbWVhc3VyZWRfcG9z",
            "aXRpb25zGAMgASgLMiQua3VrYS5tb3Rpb24uZXh0ZXJuYWwuSm9pbnRQb3Np",
            "dGlvbnMSQgoTbWVhc3VyZWRfdmVsb2NpdGllcxgEIAEoCzIlLmt1a2EubW90",
            "aW9uLmV4dGVybmFsLkpvaW50VmVsb2NpdGllcxI8ChBtZWFzdXJlZF90b3Jx",
            "dWVzGAUgASgLMiIua3VrYS5tb3Rpb24uZXh0ZXJuYWwuSm9pbnRUb3JxdWVz",
            "QocBChhjb20ua3VrYS5tb3Rpb24uZXh0ZXJuYWxCGE1vdGlvblN0YXRlSW50",
            "ZXJuYWxQcm90b1ABWjhnb2xhbmcucmQua3VrYS5jb20vbW90aW9uLWFwaS9w",
            "cm90by9rdWthL21vdGlvbi9leHRlcm5hbKoCFEt1a2EuTW90aW9uLkV4dGVy",
            "bmFsYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Kuka.Motion.External.UtilsReflection.Descriptor, global::Kuka.Motion.External.ExternalControlModeReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Kuka.Motion.External.MotionStateInternal), global::Kuka.Motion.External.MotionStateInternal.Parser, new[]{ "IpoStopped", "ControlMode", "MeasuredPositions", "MeasuredVelocities", "MeasuredTorques" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Internal message for SharedMem Communication between ecs and external sampler
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class MotionStateInternal : pb::IMessage<MotionStateInternal>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MotionStateInternal> _parser = new pb::MessageParser<MotionStateInternal>(() => new MotionStateInternal());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MotionStateInternal> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Kuka.Motion.External.MotionStateInternalReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MotionStateInternal() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MotionStateInternal(MotionStateInternal other) : this() {
      ipoStopped_ = other.ipoStopped_;
      controlMode_ = other.controlMode_;
      measuredPositions_ = other.measuredPositions_ != null ? other.measuredPositions_.Clone() : null;
      measuredVelocities_ = other.measuredVelocities_ != null ? other.measuredVelocities_.Clone() : null;
      measuredTorques_ = other.measuredTorques_ != null ? other.measuredTorques_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MotionStateInternal Clone() {
      return new MotionStateInternal(this);
    }

    /// <summary>Field number for the "ipo_stopped" field.</summary>
    public const int IpoStoppedFieldNumber = 1;
    private bool ipoStopped_;
    /// <summary>
    /// Flag indicating whether the command handling has stopped
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IpoStopped {
      get { return ipoStopped_; }
      set {
        ipoStopped_ = value;
      }
    }

    /// <summary>Field number for the "control_mode" field.</summary>
    public const int ControlModeFieldNumber = 2;
    private global::Kuka.Motion.External.ExternalControlMode controlMode_ = global::Kuka.Motion.External.ExternalControlMode.Unspecified;
    /// <summary>
    /// Currently used control mode
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Kuka.Motion.External.ExternalControlMode ControlMode {
      get { return controlMode_; }
      set {
        controlMode_ = value;
      }
    }

    /// <summary>Field number for the "measured_positions" field.</summary>
    public const int MeasuredPositionsFieldNumber = 3;
    private global::Kuka.Motion.External.JointPositions measuredPositions_;
    /// <summary>
    /// The measured joint position of the current cycle
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Kuka.Motion.External.JointPositions MeasuredPositions {
      get { return measuredPositions_; }
      set {
        measuredPositions_ = value;
      }
    }

    /// <summary>Field number for the "measured_velocities" field.</summary>
    public const int MeasuredVelocitiesFieldNumber = 4;
    private global::Kuka.Motion.External.JointVelocities measuredVelocities_;
    /// <summary>
    /// The measured joint velocities of the current cycle
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Kuka.Motion.External.JointVelocities MeasuredVelocities {
      get { return measuredVelocities_; }
      set {
        measuredVelocities_ = value;
      }
    }

    /// <summary>Field number for the "measured_torques" field.</summary>
    public const int MeasuredTorquesFieldNumber = 5;
    private global::Kuka.Motion.External.JointTorques measuredTorques_;
    /// <summary>
    /// The measured joint torques of the current cycle
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Kuka.Motion.External.JointTorques MeasuredTorques {
      get { return measuredTorques_; }
      set {
        measuredTorques_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MotionStateInternal);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MotionStateInternal other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IpoStopped != other.IpoStopped) return false;
      if (ControlMode != other.ControlMode) return false;
      if (!object.Equals(MeasuredPositions, other.MeasuredPositions)) return false;
      if (!object.Equals(MeasuredVelocities, other.MeasuredVelocities)) return false;
      if (!object.Equals(MeasuredTorques, other.MeasuredTorques)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (IpoStopped != false) hash ^= IpoStopped.GetHashCode();
      if (ControlMode != global::Kuka.Motion.External.ExternalControlMode.Unspecified) hash ^= ControlMode.GetHashCode();
      if (measuredPositions_ != null) hash ^= MeasuredPositions.GetHashCode();
      if (measuredVelocities_ != null) hash ^= MeasuredVelocities.GetHashCode();
      if (measuredTorques_ != null) hash ^= MeasuredTorques.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (IpoStopped != false) {
        output.WriteRawTag(8);
        output.WriteBool(IpoStopped);
      }
      if (ControlMode != global::Kuka.Motion.External.ExternalControlMode.Unspecified) {
        output.WriteRawTag(16);
        output.WriteEnum((int) ControlMode);
      }
      if (measuredPositions_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(MeasuredPositions);
      }
      if (measuredVelocities_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(MeasuredVelocities);
      }
      if (measuredTorques_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(MeasuredTorques);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (IpoStopped != false) {
        output.WriteRawTag(8);
        output.WriteBool(IpoStopped);
      }
      if (ControlMode != global::Kuka.Motion.External.ExternalControlMode.Unspecified) {
        output.WriteRawTag(16);
        output.WriteEnum((int) ControlMode);
      }
      if (measuredPositions_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(MeasuredPositions);
      }
      if (measuredVelocities_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(MeasuredVelocities);
      }
      if (measuredTorques_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(MeasuredTorques);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (IpoStopped != false) {
        size += 1 + 1;
      }
      if (ControlMode != global::Kuka.Motion.External.ExternalControlMode.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ControlMode);
      }
      if (measuredPositions_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MeasuredPositions);
      }
      if (measuredVelocities_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MeasuredVelocities);
      }
      if (measuredTorques_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MeasuredTorques);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MotionStateInternal other) {
      if (other == null) {
        return;
      }
      if (other.IpoStopped != false) {
        IpoStopped = other.IpoStopped;
      }
      if (other.ControlMode != global::Kuka.Motion.External.ExternalControlMode.Unspecified) {
        ControlMode = other.ControlMode;
      }
      if (other.measuredPositions_ != null) {
        if (measuredPositions_ == null) {
          MeasuredPositions = new global::Kuka.Motion.External.JointPositions();
        }
        MeasuredPositions.MergeFrom(other.MeasuredPositions);
      }
      if (other.measuredVelocities_ != null) {
        if (measuredVelocities_ == null) {
          MeasuredVelocities = new global::Kuka.Motion.External.JointVelocities();
        }
        MeasuredVelocities.MergeFrom(other.MeasuredVelocities);
      }
      if (other.measuredTorques_ != null) {
        if (measuredTorques_ == null) {
          MeasuredTorques = new global::Kuka.Motion.External.JointTorques();
        }
        MeasuredTorques.MergeFrom(other.MeasuredTorques);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            IpoStopped = input.ReadBool();
            break;
          }
          case 16: {
            ControlMode = (global::Kuka.Motion.External.ExternalControlMode) input.ReadEnum();
            break;
          }
          case 26: {
            if (measuredPositions_ == null) {
              MeasuredPositions = new global::Kuka.Motion.External.JointPositions();
            }
            input.ReadMessage(MeasuredPositions);
            break;
          }
          case 34: {
            if (measuredVelocities_ == null) {
              MeasuredVelocities = new global::Kuka.Motion.External.JointVelocities();
            }
            input.ReadMessage(MeasuredVelocities);
            break;
          }
          case 42: {
            if (measuredTorques_ == null) {
              MeasuredTorques = new global::Kuka.Motion.External.JointTorques();
            }
            input.ReadMessage(MeasuredTorques);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            IpoStopped = input.ReadBool();
            break;
          }
          case 16: {
            ControlMode = (global::Kuka.Motion.External.ExternalControlMode) input.ReadEnum();
            break;
          }
          case 26: {
            if (measuredPositions_ == null) {
              MeasuredPositions = new global::Kuka.Motion.External.JointPositions();
            }
            input.ReadMessage(MeasuredPositions);
            break;
          }
          case 34: {
            if (measuredVelocities_ == null) {
              MeasuredVelocities = new global::Kuka.Motion.External.JointVelocities();
            }
            input.ReadMessage(MeasuredVelocities);
            break;
          }
          case 42: {
            if (measuredTorques_ == null) {
              MeasuredTorques = new global::Kuka.Motion.External.JointTorques();
            }
            input.ReadMessage(MeasuredTorques);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
